services:
  cat-database-microservice:
    build: ./cat-database-microservice
    ports:
      - "${PORT_CAT_DB}:${PORT_CAT_DB}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT_CAT_DB}
    volumes:
      - ./cat-database-microservice/uploads:/app/uploads
    depends_on:
      - mongo
    
  auth-microservice:
    build: ./auth-microservice
    ports:
      - "${PORT_AUTH}:${PORT_AUTH}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT_AUTH}
    depends_on:
      - mongo

  favorites-microservice:
    build: ./favorites-microservice
    ports:
      - "${PORT_FAVORITES}:${PORT_FAVORITES}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT_FAVORITES}
    depends_on:
      - mongo

  preferences-microservice:
    build: ./preferences-microservice
    ports:
      - "${PORT_PREFERENCES}:${PORT_PREFERENCES}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT_PREFERENCES}
      - AUTH_SERVICE_URL=${URL_AUTH}
    depends_on:
      - mongo
  
  recommender-microservice:
    build: ./recommender-microservice
    ports:
      - "${PORT_RECOMMENDER}:${PORT_RECOMMENDER}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT_RECOMMENDER}
      - PREFERENCES_SERVICE_URL=${URL_PREFERENCES}
      - FAVORITES_SERVICE_URL=${URL_FAVORITES}
      - CAT_DATABASE_URL=${URL_CAT_DB}
    depends_on:
      - mongo
      - cat-database-microservice
      - favorites-microservice
      - preferences-microservice

  frontend:
    build: 
      context: ./CatCall-Frontend
      args:
        VITE_AUTH_URL: ${VITE_AUTH_URL}
        VITE_CAT_DB_URL: ${VITE_CAT_DB_URL}
        VITE_FAVORITES_SERVICE_URL: ${VITE_FAVORITES_SERVICE_URL}
        VITE_PREFERENCES_DB_URL: ${VITE_PREFERENCES_DB_URL}
        VITE_RECOMMENDER_SERVICE_URL: ${VITE_RECOMMENDER_SERVICE_URL}
    ports:
      - "${PORT_FRONTEND}:80"
    depends_on:
      - cat-database-microservice
      - auth-microservice
      - favorites-microservice
      - preferences-microservice
      - recommender-microservice


  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
